"""F3 — filled official 2025 Form 1040 PDF tests (test leg).

Proves:
- Filling the vendored official 2025 Form 1040 with a sample computed return + identity
  yields a flattened PDF whose **extracted page text** contains the taxpayer name and the
  computed dollar amounts (so the values are real page content, viewer-independent).
- Every field name the map targets still exists in the vendored form's ``get_fields()``
  (guards against an IRS re-post that renumbers fields — ARCHITECTURE / research note).
- The filing-status checkbox is set to its on-value, and the ``/XFA`` layer is dropped.

The companion **sign-off** leg (a human eyeballs ``fixtures/sample_filled_1040.pdf`` in a
viewer) is generated by ``generate_sample_fixture`` and is the human's to confirm.
"""

from __future__ import annotations

import io
from decimal import Decimal
from pathlib import Path

import pytest
from pypdf import PdfReader

from app.pdf import field_map as fm
from app.pdf.fill import VENDORED_FORM_PATH, fill_1040
from app.tax.compute import compute_return
from app.tax.constants_2025 import FilingStatus
from app.w2.build_fixture import build_fixture
from app.w2.extract import extract_w2_from_bytes

REPO_ROOT = Path(__file__).resolve().parents[1]
SAMPLE_OUTPUT_PATH = REPO_ROOT / "fixtures" / "sample_filled_1040.pdf"


@pytest.fixture(scope="module")
def w2_identity(tmp_path_factory):
    """Parse the F2 fake-W-2 fixture into a validated W2 (built to a temp path)."""
    tmp = tmp_path_factory.mktemp("w2") / "fake_w2.pdf"
    build_fixture(tmp)
    return extract_w2_from_bytes(tmp.read_bytes())


@pytest.fixture(scope="module")
def computed_single(w2_identity):
    """An F1 computed return for the fixture profile (single filer, ~$40k W-2)."""
    return compute_return(
        wages=Decimal(str(w2_identity.wages)),
        withholding=Decimal(str(w2_identity.fed_withholding)),
        filing_status=FilingStatus.SINGLE,
    )


@pytest.fixture(scope="module")
def filled_pdf_bytes(computed_single, w2_identity):
    return fill_1040(computed_single, w2_identity, FilingStatus.SINGLE)


def _all_pages_text(pdf_bytes: bytes) -> str:
    reader = PdfReader(io.BytesIO(pdf_bytes))
    return "\n".join(page.extract_text() for page in reader.pages)


# --- Field-map integrity (guards against an IRS re-post) ----------------------


def test_vendored_form_exists():
    assert VENDORED_FORM_PATH.exists(), f"vendored form missing: {VENDORED_FORM_PATH}"


def test_every_mapped_field_exists_in_vendored_form():
    """Every name in field_map must still be a real field in the vendored 1040."""
    reader = PdfReader(str(VENDORED_FORM_PATH))
    fields = reader.get_fields()
    assert fields, "vendored form exposes no AcroForm fields"
    field_names = set(fields.keys())

    missing = [name for name in fm.ALL_FIELD_NAMES if name not in field_names]
    assert not missing, f"mapped field(s) no longer in vendored form: {missing}"


def test_filing_status_checkboxes_use_on_value_1():
    """Each filing-status checkbox's on-value is /1 (NOT /Yes) — read from /_States_."""
    reader = PdfReader(str(VENDORED_FORM_PATH))
    fields = reader.get_fields()
    for name in fm.CHECKBOX_FIELD_NAMES:
        states = fields[name].get("/_States_")
        assert states is not None, f"{name} has no /_States_"
        assert fm.CHECKBOX_ON_VALUE in states, f"{name} states {states} lacks {fm.CHECKBOX_ON_VALUE}"


def test_field_map_covers_required_lines():
    """The map must cover the guaranteed-core identity + numeric lines + filing status."""
    required = (
        fm.FIELD_FIRST_NAME,
        fm.FIELD_LAST_NAME,
        fm.FIELD_SSN,
        fm.FIELD_ADDRESS_STREET,
        fm.FIELD_LINE_1A_WAGES,
        fm.FIELD_LINE_1Z_TOTAL_WAGES,
        fm.FIELD_LINE_9_TOTAL_INCOME,
        fm.FIELD_LINE_11B_AGI,
        fm.FIELD_LINE_12_STANDARD_DEDUCTION,
        fm.FIELD_LINE_15_TAXABLE_INCOME,
        fm.FIELD_LINE_16_TAX,
        fm.FIELD_LINE_24_TOTAL_TAX,
        fm.FIELD_LINE_25A_WITHHOLDING,
        fm.FIELD_LINE_33_TOTAL_PAYMENTS,
        fm.FIELD_LINE_34_REFUND,
        fm.FIELD_LINE_37_AMOUNT_OWED,
    )
    for name in required:
        assert name in fm.ALL_FIELD_NAMES
    # All four filing statuses map to a checkbox.
    for status in FilingStatus:
        assert status in fm.FILING_STATUS_CHECKBOX


# --- Fill produces a real, populated PDF -------------------------------------


def test_filled_pdf_is_a_pdf(filled_pdf_bytes):
    assert filled_pdf_bytes[:5] == b"%PDF-"
    reader = PdfReader(io.BytesIO(filled_pdf_bytes))
    assert len(reader.pages) == 2


def test_filled_pdf_drops_xfa(filled_pdf_bytes):
    """The /XFA layer must be gone so Acrobat honors the AcroForm values."""
    reader = PdfReader(io.BytesIO(filled_pdf_bytes))
    acro = reader.trailer["/Root"].get("/AcroForm")
    if acro is not None:
        assert "/XFA" not in acro.get_object()


def test_taxpayer_name_in_extracted_text(filled_pdf_bytes, w2_identity):
    """The taxpayer's first and last name appear in the flattened page text."""
    text = _all_pages_text(filled_pdf_bytes)
    first, *rest = w2_identity.employee_name.split()
    last = rest[-1] if rest else ""
    assert first in text, f"first name {first!r} not in extracted text"
    assert last in text, f"last name {last!r} not in extracted text"


def test_computed_dollar_amounts_in_extracted_text(filled_pdf_bytes, computed_single):
    """The key computed dollar amounts are present as real page content."""
    text = _all_pages_text(filled_pdf_bytes)

    expected_amounts = {
        "wages": str(int(computed_single.wages)),
        "standard_deduction": str(int(computed_single.standard_deduction)),
        "taxable_income": str(int(computed_single.taxable_income)),
        "tax": str(int(computed_single.tax)),
        "withholding": str(int(computed_single.withholding)),
    }
    # Refund XOR amount owed — whichever is non-zero.
    if computed_single.refund > Decimal("0"):
        expected_amounts["refund"] = str(int(computed_single.refund))
    else:
        expected_amounts["amount_owed"] = str(int(computed_single.amount_owed))

    missing = {k: v for k, v in expected_amounts.items() if v not in text}
    assert not missing, f"computed amounts not found in PDF text: {missing}"


def test_masked_ssn_in_text_raw_ssn_absent(filled_pdf_bytes, w2_identity):
    """The masked SSN is filled; the raw 9-digit SSN never appears in the PDF."""
    text = _all_pages_text(filled_pdf_bytes)
    assert w2_identity.masked_ssn in text
    # The raw SSN digits (123456789 / 123-45-6789) must not be present.
    assert "123-45-6789" not in text
    assert "123456789" not in text


def test_filing_status_checkbox_set(filled_pdf_bytes):
    """The Single filing-status checkbox carries its on-value in the filled form."""
    reader = PdfReader(io.BytesIO(filled_pdf_bytes))
    fields = reader.get_fields() or {}
    single = fields.get(fm.FIELD_FILING_STATUS_SINGLE)
    assert single is not None
    assert single.get("/V") in (fm.CHECKBOX_ON_VALUE, "/1")


@pytest.mark.parametrize("status", list(FilingStatus))
def test_fill_works_for_all_statuses(w2_identity, status):
    """Filling succeeds for every filing status (deduction/tax differ; fill must not crash)."""
    computed = compute_return(
        wages=Decimal(str(w2_identity.wages)),
        withholding=Decimal(str(w2_identity.fed_withholding)),
        filing_status=status,
    )
    pdf_bytes = fill_1040(computed, w2_identity, status)
    assert pdf_bytes[:5] == b"%PDF-"
    text = _all_pages_text(pdf_bytes)
    # The status-specific standard deduction shows up in the text.
    assert str(int(computed.standard_deduction)) in text


# --- Sign-off fixture generation ---------------------------------------------


def generate_sample_fixture() -> Path:
    """Generate ``fixtures/sample_filled_1040.pdf`` from the F2 W-2 + an F1 single return.

    This is the artifact for the human SIGN-OFF leg: the parent renders it and the user
    eyeballs that it reads as a genuinely completed 1040 in a viewer.
    """
    fixtures_dir = REPO_ROOT / "fixtures"
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    fake_w2 = fixtures_dir / "fake_w2.pdf"
    build_fixture(fake_w2)
    w2 = extract_w2_from_bytes(fake_w2.read_bytes())
    computed = compute_return(
        wages=Decimal(str(w2.wages)),
        withholding=Decimal(str(w2.fed_withholding)),
        filing_status=FilingStatus.SINGLE,
    )
    pdf_bytes = fill_1040(computed, w2, FilingStatus.SINGLE)
    SAMPLE_OUTPUT_PATH.write_bytes(pdf_bytes)
    return SAMPLE_OUTPUT_PATH


def test_generate_sample_filled_1040():
    """Generate (and smoke-check) the sign-off sample PDF as part of the test run."""
    path = generate_sample_fixture()
    assert path.exists()
    data = path.read_bytes()
    assert data[:5] == b"%PDF-"
    text = "\n".join(p.extract_text() for p in PdfReader(io.BytesIO(data)).pages)
    # Sanity: the sample carries the fixture taxpayer + the single-filer refund figure.
    assert "Alex" in text
    assert "Taxpayer" in text


if __name__ == "__main__":
    out = generate_sample_fixture()
    print(f"Wrote sign-off sample: {out}")
